@domain = app.lvh.voronenko.net
@domain_endpoint = http://app.lvh.voronenko.net:8000

@contentType = application/json
@createdAt = {{$datetime iso8601}}
@modifiedBy = {{$processEnv USERNAME}}

@companyname = voronenko

@kong = http://localhost:8001

@m2mservice_name = m2mservice

@jwtservicename = example-service-m2m
@jwttesturi =direct

### create direct route service

curl -i -X POST \
--url {{ kong }}/services/ \
--data 'name={{ m2mservice_name }}' \
--data 'url=https://httpbin.org/get'

###  Create direct route
curl -i -X POST \
--url {{ kong }}/services/{{ m2mservice_name }}/routes \
--data 'hosts[]={{domain}}&paths[]=/direct'

### check route is up
curl --request GET \
  --url {{ domain_endpoint }}/direct

### Activate jwt plugin for service

curl -i -X POST \
  --url {{kong}}/services/{{ m2mservice_name }}/plugins/ \
  --data 'name=jwt'

### consume direct route
curl --request GET \
  --url {{ domain_endpoint }}/direct

###

###
@auth0consumer=auth0voronenko
@pubkeyname={{companyname}}.pub

curl -i -X POST \
  --url {{ kong }}/consumers/ \
  --data "username={{auth0consumer}}&custom_id=someid2"


###
# Execute shell kind of

# #!/bin/bash

# COMPANYNAME=voronenko
# CONSUMERNAME=auth0voronenko
# curl -i -X POST http://localhost:8001/consumers/${CONSUMERNAME}/jwt \
#     -F "algorithm=RS256" \
#     -F "rsa_public_key=@./${COMPANYNAME}.pub" \
#     -F "key=https://${COMPANYNAME}.auth0.com/"

# Check assign_jwt_creds.sh in the current dir

###

@consumerkey="-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA2HUmzrnbV+7N4wwMsTUt\n2RlP3e\/giUxkzddl12V8Jp4QlylXkP\/5zRgYvCuZbhYcpq50JwW9KuDsPfDVq\/bk\nA17i+doZNe\/ZN2y70\/t15UuHgpaAKEyWqHsos0SXjVJznBnMYw2AkxAij+j03PbD\nhw1m4cg4lrouLBPhE5ibZ+43nL3\/qEGoFVGLs1fEC7l5QOS0ZAMk+lfvybFkKhpB\nUARXvojXZ06Ssi7FJ89vDO7yJoNaXRPceWFqNbpc6WAr8SsSL+3Sw7H7hggLpxcE\nwqA5Enw4D1L5tiBTpaLu1yeHgiuYgvIdSeYtshSL7Fc3zDWfh4LcIiAxscqifNjm\nLwIDAQAB\n-----END PUBLIC KEY-----\n"

curl -i -X POST {{ kong }}/consumers/{{ auth0consumer }}/jwt \
    -F "algorithm=RS256" \
    -F "rsa_public_key={{ consumerkey }}" \
    -F "key=https://{{ companyname }}.auth0.com/"


### Now time to test the api

# @name accessTokenRequest
curl --request POST \
  --url https://{{companyname}}.auth0.com/oauth/token \
  --header 'content-type: application/json' \
  --data '{"client_id":"R477zd0dhD0Hq3CnNIEgE677nwboYD5u","client_secret":"Omps9OmF5j_gNJBfc6byC3i6YuokRhVxtUG3THzEpKtOau8mgq9qAUZ6FxhxIHm2","audience":"https://implicitgrant.auth0.voronenko.net","grant_type":"client_credentials"}'

###
@accessToken = {{accessTokenRequest.response.body.$.access_token}}

GET {{domain_endpoint}}/direct
authorization: Bearer {{accessToken}}


### Dirty

GET {{domain_endpoint}}/direct
authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6IlF6bEZOak5CUmtZNVJqY3lOVVpCUmpJMU5qRkJOMFl4T0VNMVJFSXhNelU0TVVJeU5qa3dSUSJ9.eyJodHRwczovL2Zvby5jb20vY2xhaW0iOiJiYXIiLCJpc3MiOiJodHRwczovL3Zvcm9uZW5rby5hdXRoMC5jb20vIiwic3ViIjoiUjQ3N3pkMGRoRDBIcTNDbk5JRWdFNjc3bndib1lENXVAY2xpZW50cyIsImF1ZCI6Imh0dHBzOi8vaW1wbGljaXRncmFudC5hdXRoMC52b3JvbmVua28ubmV0IiwiaWF0IjoxNTc4MzEwOTYwLCJleHAiOjE1NzgzOTczNjAsImF6cCI6IlI0Nzd6ZDBkaEQwSHEzQ25OSUVnRTY3N253Ym9ZRDV1IiwiZ3R5IjoiY2xpZW50LWNyZWRlbnRpYWxzIn0.nV-RZCBAwQOadofGIcNJqZvYppTFCtaVOVHBtSMKxjxNgHNiDO_VBX6OdvRDkNQkQgd3r6oFTyNaHCbZ_Ymp5F4kNuwiAyG5NinF8Bkyzq74RVL_3isF5hypyrwIb__b9Mfne-KWD36N-BtmfDuMCKA0c4EFfUrBmB9k-E3qjZ6MXgnbaEQV84cz8PWmnuqgTQSCmc14gjCzeRo5PqFGLyWLN7R3OHSO4tzQyHdcLNDnolJxzzB47l5Ad_6WfZgYK8izLmLKAgOpVQv5hDM2aA1RnEfpFu_x5e2G_VWlq4cCzGqhjXNM3Vl7_fMfv4lEBKGmBllebGbpdYy0Z6eQsg

### To spa


GET {{domain_endpoint}}/spa/
authorization: Bearer {{accessToken}}


#####################################################3

# Protecting with sa-jwt-claims-validate

### Activate sa-jwt-claims-validate plugin for service
POST {{kong}}/services/{{ m2mservice_name }}/plugins/ HTTP/1.1
content-type: application/json

{
       "name": "sa-jwt-claims-validate",
       "config": {
         "claims": {
             "iss": "https://voronenko.auth0.com/",
             "https://foo.com/claim": "barr"
         }
       }
}

